apps/webssh/urls.py
from django.urls import path
from . import views


app_name = "webssh"
urlpatterns = [
    path('hosts/', views.hosts, name='hosts'),
    path('terminal/', views.terminal, name='terminal'),
    path('terminal/cli/', views.terminal_cli, name='terminal_cli'),
    path('terminal/cli/sftp', views.terminal_cli_sftp, name='terminal_cli_sftp'),
    path('terminal/view/', views.terminal_view, name='terminal_view'),
    path('terminal/clissh/view/', views.terminal_clissh_view, name='terminal_clissh_view'),
    path('logs/', views.logs, name='logs'),
    path('sessions/', views.sessions, name='sessions'),
]

devops/urls.py
# from django.contrib import admin
from django.urls import path, include, re_path
from server.views import index
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    # path('admin/', admin.site.urls),
    
    path('', index),
    
    path('server/', include('server.urls', namespace='server')),
    path('api/server/', include('server.urls_api', namespace='server_api')),
    
    path('user/', include('user.urls', namespace='user')),
    path('api/user/', include('user.urls_api', namespace='user_api')),
    
    path('webssh/', include('webssh.urls', namespace='webssh')),
    path('api/webssh/', include('webssh.urls_api', namespace='webssh_api')),

    path('webtelnet/', include('webtelnet.urls', namespace='webtelnet')),

    path('webguacamole/', include('webguacamole.urls', namespace='webguacamole')),

    path('batch/', include('batch.urls', namespace='batch')),
    path('api/batch/', include('batch.urls_api', namespace='batch_api')),

]

"""
正式部署时一般静态文件直接用 nginx 转发，django 本身处理动态请求
"""
if settings.DEBUG:  # debug 模式下加载 /media 静态资源
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if not settings.DEBUG:  # 非 debug 模式下加载 /static 静态资源，debug 模式下 django 开发服务器会默认加载静态资源
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

apps/server/models.py
from django.db import models
# Create your models here.


class HostGroup(models.Model):
    group_name = models.CharField(max_length=128, verbose_name="组名")
    # 用户删除时，相关的主机组也删除
    user = models.ForeignKey('user.User', on_delete=models.CASCADE, verbose_name="归属用户")
    memo = models.TextField(blank=True, null=True, verbose_name="备注")
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')

    def __str__(self):
        return self.group_name

    class Meta:
        ordering = ["-create_time"]
        verbose_name = '主机组'
        verbose_name_plural = "主机组"
        unique_together = ('group_name', 'user')  # 同一用户下，主机组必须唯一


class RemoteUser(models.Model):
    """
    名称唯一，用户名可以重复，不同主机登陆用户名相同，密码不同
    """
    name = models.CharField(unique=True, max_length=128, verbose_name="名称")
    username = models.CharField(max_length=128, verbose_name="用户名")
    password = models.CharField(max_length=512, verbose_name="密码")
    enabled = models.BooleanField(default=False, verbose_name='登陆后是否su跳转超级用户')
    superusername = models.CharField(max_length=128, blank=True, null=True, verbose_name="超级用户")
    superpassword = models.CharField(max_length=512, blank=True, null=True, verbose_name="超级密码")
    memo = models.TextField(blank=True, null=True, verbose_name='备注')
    create_time = models.DateTimeField('添加时间', auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["-create_time"]
        verbose_name = "主机账户"
        verbose_name_plural = "主机账户"


class RemoteUserBindHost(models.Model):
    PROTOCOL_CHOICES = (    # 目前支持ssh, telnet
        (1, 'ssh'),
        (2, 'telnet'),
        (3, 'rdp'),
        (4, 'vnc'),
        (5, 'sftp'),
        (6, 'ftp'),
    )
    TYPE_CHOICES = (
        (1, '服务器'),
        (2, '防火墙'),
        (3, '路由器'),
        (4, '二层交换机'),
        (5, '三层交换机'),
        (6, '虚拟机'),
        (7, 'PC机'),
    )
    ENV_CHOICES = (
        (1, '正式环境'),
        (2, '测试环境'),
    )
    PLATFORM_CHOICES = (
        (1, 'linux'),
        (2, 'windows'),
        (3, 'unix'),
    )
    hostname = models.CharField(max_length=128, unique=True, verbose_name='主机名')
    type = models.SmallIntegerField(default=1, choices=TYPE_CHOICES, verbose_name='类型')
    ip = models.GenericIPAddressField(verbose_name='主机IP')  # 做了ip映射，ip可能重复，ip:port 不会重复
    wip = models.GenericIPAddressField(verbose_name='公网IP', blank=True, null=True)
    protocol = models.SmallIntegerField(default=1, choices=PROTOCOL_CHOICES, verbose_name='协议')
    env = models.SmallIntegerField(default=1, choices=ENV_CHOICES, verbose_name='环境')
    host_group = models.ManyToManyField('HostGroup', blank=True, verbose_name="主机组")
    port = models.SmallIntegerField(default=22, verbose_name='端口')
    release = models.CharField(max_length=255, default='CentOS', verbose_name='系统/型号')
    platform = models.SmallIntegerField(default=1, choices=PLATFORM_CHOICES, verbose_name='平台')
    memo = models.TextField(blank=True, null=True, verbose_name='备注')
    # on_delete 当 RemoteUser 记录被删时，阻止其操作
    remote_user = models.ForeignKey('RemoteUser', blank=True, null=True, on_delete=models.PROTECT)
    enabled = models.BooleanField(default=True, verbose_name='是否启用')
    create_time = models.DateTimeField('添加时间', auto_now_add=True)

    def __str__(self):
        return self.hostname

    class Meta:
        ordering = ["-create_time"]
        verbose_name = '远程主机'
        verbose_name_plural = '远程主机'
        unique_together = ('ip', 'protocol', 'port', 'remote_user')
        # 一个用户下，只能绑定同一个主机一次，不能一个用户下绑定两个相同主机


class ServerDetail(models.Model):
    # 远程主机删除此，serverdetail 相关数据也删除
    server = models.OneToOneField('RemoteUserBindHost', on_delete=models.CASCADE)
    cpu_model = models.CharField(max_length=128, blank=True, null=True, verbose_name='CPU型号')
    cpu_number = models.SmallIntegerField(blank=True, null=True, verbose_name='物理CPU个数')
    vcpu_number = models.SmallIntegerField(blank=True, null=True, verbose_name='逻辑CPU个数')
    disk_total = models.CharField(max_length=16, blank=True, null=True, verbose_name='磁盘空间')
    ram_total = models.SmallIntegerField(blank=True, null=True, verbose_name='内存容量')
    swap_total = models.SmallIntegerField(blank=True, null=True, verbose_name='交换空间容量')
    kernel = models.CharField(max_length=128, blank=True, null=True, verbose_name='内核版本')
    system = models.CharField(max_length=128, blank=True, null=True, verbose_name='操作系统')
    filesystems = models.TextField(blank=True, null=True, verbose_name='文件系统')
    interfaces = models.TextField(blank=True, null=True, verbose_name='网卡信息')
    server_model = models.CharField(max_length=128, blank=True, null=True, verbose_name='型号')

    class Meta:
        verbose_name = '主机详细'
        verbose_name_plural = '主机详细'

apps/webssh/models.py
from django.db import models
# Create your models here.


class TerminalLog(models.Model):
    user = models.CharField(max_length=64, verbose_name='操作人')
    hostname = models.CharField(max_length=128, verbose_name='主机名')
    ip = models.GenericIPAddressField(verbose_name='主机IP')
    protocol = models.CharField(max_length=64, default='ssh', verbose_name="协议")
    port = models.SmallIntegerField(default=22, verbose_name='端口')
    username = models.CharField(max_length=128, verbose_name="用户名")
    cmd = models.TextField('命令详情', blank=True, null=True)
    detail = models.CharField(max_length=128, blank=True, null=True, verbose_name="结果详情(文件名)")
    address = models.GenericIPAddressField('IP地址', blank=True, null=True)
    useragent = models.CharField(max_length=512, blank=True, null=True, verbose_name='User_Agent')
    start_time = models.DateTimeField('会话开始时间')
    create_time = models.DateTimeField('事件时间', auto_now_add=True)

    def __str__(self):
        return self.user

    class Meta:
        ordering = ["-create_time"]
        verbose_name = '在线会话日志'
        verbose_name_plural = '在线会话日志'


class TerminalSession(models.Model):
    PROTOCOL_CHOICES = (    # 目前支持ssh, telnet
        (1, 'ssh'),
        (2, 'telnet'),
        (3, 'rdp'),
        (4, 'vnc'),
        (5, 'sftp'),
        (6, 'ftp'),
    )

    TYPE_CHOICES = (
        (1, 'webssh'),
        (2, 'websftp'),
        (3, 'clissh'),
        (4, 'clisftp'),
        (5, 'webtelnet'),
        (6, 'clitelnet'),
        (7, 'webrdp'),
        (8, 'webvnc'),
    )

    name = models.CharField(max_length=512, verbose_name='会话名称')
    group = models.CharField(default='chat_default', max_length=512, verbose_name='会话组')
    type = models.SmallIntegerField(default=1, choices=TYPE_CHOICES, verbose_name='类型')
    user = models.CharField(max_length=128, verbose_name='用户')
    host = models.GenericIPAddressField(verbose_name='主机')
    port = models.SmallIntegerField(default=22, verbose_name='端口')
    username = models.CharField(max_length=128, verbose_name='账号')
    protocol = models.SmallIntegerField(default=1, choices=PROTOCOL_CHOICES, verbose_name='协议')
    address = models.GenericIPAddressField('IP地址', blank=True, null=True)
    useragent = models.CharField(max_length=512, blank=True, null=True, verbose_name='User_Agent')
    locked = models.BooleanField(default=False, verbose_name='会话状态')
    create_time = models.DateTimeField('会话时间', auto_now_add=True)

    def __str__(self):
        return '{0}'.format(self.name)

    class Meta:
        ordering = ["-create_time"]
        verbose_name = '在线会话'
        verbose_name_plural = '在线会话'

apps/webssh/forms.py
from django import forms


class HostForm(forms.Form):
    hostid = forms.IntegerField(label="主机id")


class SessionViewForm(forms.Form):
    sessionname = forms.CharField(label="会话名称")
    group = forms.CharField(label="会话组")

apps/webssh/views.py
from django.shortcuts import render, HttpResponse
from server.models import RemoteUserBindHost
from .models import TerminalLog, TerminalSession
from user.models import User
from util.tool import login_required, post_required, gen_rand_char
from django.http import JsonResponse
from django.db.models import Q
from .forms import HostForm, SessionViewForm
from django.core.cache import cache
from django.conf import settings
from ratelimit.decorators import ratelimit      # 限速
from ratelimit import ALL
from util.rate import rate, key
import json
import logging
logging.basicConfig(level=logging.INFO, format='[%(asctime)s] - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)
# Create your views here.


@ratelimit(key=key, rate=rate, method=ALL, block=True)
@login_required
def hosts(request):
    if request.session['issuperuser'] and request.session['username'] == 'admin':
        hosts = RemoteUserBindHost.objects.filter(enabled=True)
    else:
        hosts = RemoteUserBindHost.objects.filter(
            Q(user__username=request.session['username']) | Q(group__user__username=request.session['username']),
            enabled=True
        ).distinct()
    return render(request, 'webssh/hosts.html', locals())


@ratelimit(key=key, rate=rate, method=ALL, block=True)
@login_required
@post_required
def terminal(request):
    host_form = HostForm(request.POST)
    error_message = '请检查填写的内容!'
    if host_form.is_valid():
        host_id = host_form.cleaned_data.get('hostid')
        username = request.session.get('username')
        if request.session['issuperuser'] and request.session['username'] == 'admin':
            hosts = RemoteUserBindHost.objects.filter(
                Q(pk=host_id),
                Q(enabled=True),
            )
        else:
            hosts = RemoteUserBindHost.objects.filter(
                Q(pk=host_id),
                Q(enabled=True),
                Q(user__username=username) | Q(group__user__username=username),
            ).distinct()
        if not hosts:
            error_message = '不存在的主机!'
            return JsonResponse({"code": 400, "error": error_message})
        else:
            host = hosts[0]
            return render(request, 'webssh/terminal.html', locals())
    return JsonResponse({"code": 406, "err": error_message})


@ratelimit(key=key, rate=rate, method=ALL, block=True)
@login_required
@post_required
def terminal_cli(request):
    host_id = request.POST.get('hostid', None)
    username = request.session.get('username')
    if request.session['issuperuser'] and request.session['username'] == 'admin':
        hosts = RemoteUserBindHost.objects.filter(
            Q(pk=host_id),
            Q(enabled=True),
        )
    else:
        hosts = RemoteUserBindHost.objects.filter(
            Q(pk=host_id),
            Q(enabled=True),
            Q(user__username=username) | Q(group__user__username=username),
        ).distinct()
    if not hosts:
        error_message = '不存在的主机!'
        return JsonResponse({"code": 400, "error": error_message})
    else:
        host = hosts[0]
    password = gen_rand_char(16)    # 生成随机密码
    terminal_type = 'ssh'
    key = '%s_%s_%s' % (terminal_type, username, password)
    key_ssh = '%s_%s_%s_ssh_count' % (terminal_type, username, password)
    key_sftp = '%s_%s_%s_sftp_count' % (terminal_type, username, password)

    # cache.set(key, host_id, timeout=60 * 60 * 24)  # 写入 redis 缓存以便 proxy_sshd 读取
    cache.set(key, {'host_id': host_id, 'issuperuser': request.session['issuperuser']}, timeout=60 * 60 * 24)

    # 用于限制随机密码ssh和sftp登陆次数
    cache.set(key_ssh, 1, timeout=60 * 60 * 24)  # 写入 redis 缓存以便 proxy_sshd 读取
    if '客户端sftp' in request.session[settings.INIT_PERMISSION]['titles']:    # 判断权限
        cache.set(key_sftp, 1, timeout=60 * 60 * 24)
    user = User.objects.get(username=username)
    clissh = json.loads(user.setting)['clissh']
    ssh_app = None
    for i in clissh:
        if i['enable']:
            ssh_app = i
            break
    link_ssh = '{scheme}://%s %s' % (ssh_app['path'], ssh_app['args'])
    return HttpResponse(link_ssh.format(
        scheme='apploader',
        login_host=request.META['HTTP_HOST'].split(':')[0],
        port=settings.PROXY_SSHD.get('listen_port', 2222),
        login_user=username,
        login_passwd=password,
        host=host.ip,
        username=host.remote_user.username,
        hostname=host.hostname,
    ))


@ratelimit(key=key, rate=rate, method=ALL, block=True)
@login_required
@post_required
def terminal_cli_sftp(request):
    username = request.session.get('username')
    host_id = request.POST.get('hostid', None)
    if request.session['issuperuser'] and request.session['username'] == 'admin':
        hosts = RemoteUserBindHost.objects.filter(
            Q(pk=host_id),
            Q(enabled=True),
        )
    else:
        hosts = RemoteUserBindHost.objects.filter(
            Q(pk=host_id),
            Q(enabled=True),
            Q(user__username=username) | Q(group__user__username=username),
        ).distinct()
    if not hosts:
        error_message = '不存在的主机!'
        return JsonResponse({"code": 400, "error": error_message})
    else:
        host = hosts[0]
    password = gen_rand_char(16)    # 生成随机密码
    terminal_type = 'ssh'
    key = '%s_%s_%s' % (terminal_type, username, password)
    key_sftp = '%s_%s_%s_sftp_count' % (terminal_type, username, password)

    # cache.set(key, host_id, timeout=60 * 60 * 24)  # 写入 redis 缓存以便 proxy_sshd 读取
    cache.set(key, {'host_id': host_id, 'issuperuser': request.session['issuperuser']}, timeout=60 * 60 * 24)

    # 用于限制随机密码sftp登陆次数
    cache.set(key_sftp, 1, timeout=60 * 60 * 24)  # 写入 redis 缓存以便 proxy_sshd 读取
    user = User.objects.get(username=username)
    clisftp = json.loads(user.setting)['clisftp']
    sftp_app = None
    for i in clisftp:
        if i['enable']:
            sftp_app = i
            break
    link_sftp = '{scheme}://%s %s' % (sftp_app['path'], sftp_app['args'])
    return HttpResponse(link_sftp.format(
        scheme='apploader',
        login_host=request.META['HTTP_HOST'].split(':')[0],
        port=settings.PROXY_SSHD.get('listen_port', 2222),
        login_user=username,
        login_passwd=password,
        host=host.ip,
        username=host.remote_user.username,
        hostname=host.hostname,
    ))


@ratelimit(key=key, rate=rate, method=ALL, block=True)
@login_required
def logs(request):
    logs = TerminalLog.objects.all()
    return render(request, 'webssh/logs.html', locals())


@ratelimit(key=key, rate=rate, method=ALL, block=True)
@login_required
def sessions(request):
    sessions = TerminalSession.objects.all()
    return render(request, 'webssh/sessions.html', locals())


@ratelimit(key=key, rate=rate, method=ALL, block=True)
@login_required
@post_required
def terminal_view(request):
    sessionview_form = SessionViewForm(request.POST)
    error_message = '请检查填写的内容!'
    if sessionview_form.is_valid():
        name = sessionview_form.cleaned_data.get('sessionname')
        group = sessionview_form.cleaned_data.get('group')
        session = TerminalSession.objects.get(name=name, group=group)
        return render(request, 'webssh/terminal_view.html', locals())

    return JsonResponse({"code": 406, "err": error_message})


@ratelimit(key=key, rate=rate, method=ALL, block=True)
@login_required
@post_required
def terminal_clissh_view(request):
    sessionview_form = SessionViewForm(request.POST)
    error_message = '请检查填写的内容!'
    if sessionview_form.is_valid():
        name = sessionview_form.cleaned_data.get('sessionname')
        group = sessionview_form.cleaned_data.get('group')
        session = TerminalSession.objects.get(name=name, group=group)
        return render(request, 'webssh/terminal_clissh_view.html', locals())

    return JsonResponse({"code": 406, "err": error_message})


# 每次重启时清空在线会话表，好像使用 gunicorn 会多次加载
def cls_terminalsession():
    try:
        TerminalSession.objects.all().delete()
        logger.info('清空 TerminalSession 表')
    except Exception:
        pass


# cls_terminalsession()

templates/webssh/host_lists.html
{% extends 'base.html' %}
{% load static %}

  {% block title %}
  <title>web终端</title>
  {% endblock title %}

	{% block navheader %}
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-1">
          <div class="col-12">
            <ol class="breadcrumb">
              <li class="breadcrumb-item">作业中心</li>
              <li class="breadcrumb-item active">web终端</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
	{% endblock navheader %}
	
		  {% block content %}
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">web终端</h3>
				<div class="card-tools">
				  <button type="button" class="btn btn-tool" data-widget="collapse">
					<i class="fas fa-minus"></i>
				  </button>
				  <button type="button" class="btn btn-tool" data-widget="remove">
					<i class="fas fa-times"></i>
				  </button>
				</div>
            </div>
            <!-- /.card-header -->
            <div class="card-body table-responsive">
              <table id="datatables-lists" class="table table-bordered table-hover">
                <thead>
                <tr>
				  <th>主机ID</th>
				  <th>类型</th>
				  <th>环境</th>
				  <th>名称</th>
				  <th>IP</th>
				  <th>公网IP</th>
				  <th>协议</th>
				  <th>端口</th>
				  <th>系统</th>
				  <th>用户名</th>
				  <th>添加时间</th>
				  <th>操作</th>
                </tr>
                </thead>
                <tbody>
				{% for host in hosts %}
                <tr>
				  <td>{{ host.id }}</td>
				  <td>{{ host.host.get_type_display }}</td>
				  <td>{{ host.host.get_env_display }}</td>
				  {% if host.remote_user %}
				  <td>{{ host.host.hostname }}_{{ host.remote_user.name }}</td>
				  {% else %}
				  <td>{{ host.host.hostname }}</td>
				  {% endif %}
				  <td>{{ host.host.ip }}</td>
				  <td>{{ host.host.wip | default:'N/A' }}</td>
				  <td>{{ host.host.get_protocol_display }}</td>
				  <td>{{ host.host.port }}</td>
				  <td>{{ host.host.release }}</td>
				  {% if host.remote_user %}
				  <td>{{ host.remote_user.username }}</td>
				  {% else %}
				  <td>N/A</td>
				  {% endif %}
				  <td>{{ host.create_time|date:"Y/m/d H:i:s" }}</td>
				  <td>
					{% if host.remote_user and host.enabled %}
					{% if host.host.get_protocol_display == 'ssh' %}
					<form method="post" action="{% url 'webssh:terminal' %}" target="_blank">
					{% elif host.host.get_protocol_display == 'telnet' %}
					<form method="post" action="{% url 'webtelnet:terminal' %}" target="_blank">
					{% else %}
					<form method="post" action="#">
					{% endif %}
						{% csrf_token %}
						<input type="text" name="hostid" value="{{ host.id }}" hidden>
						<button type="submit" class="btn btn-block btn-sm btn-success btn-flat">连接</button>
					</form>
					{% else %}
					<button class="btn btn-block btn-sm btn-secondary btn-flat disabled">连接</button>
					{% endif %}
					
				  </td>
                </tr>
				{% empty %}
                <tr>没有数据！</tr>
				{% endfor %}
                </tbody>
                <tfoot>
                <tr>
				  <th>主机ID</th>
				  <th>类型</th>
				  <th>环境</th>
				  <th>名称</th>
				  <th>IP</th>
				  <th>公网IP</th>
				  <th>协议</th>
				  <th>端口</th>
				  <th>系统</th>
				  <th>用户名</th>
				  <th>添加时间</th>
				  <th>操作</th>
                </tr>
                </tfoot>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
		  {% endblock content %}

{% block js %}
<!-- DataTables -->
<script src="{% static 'adminlte/plugins/datatables/jquery.dataTables.js' %}"></script>
<script src="{% static 'adminlte/plugins/datatables/dataTables.bootstrap4.js' %}"></script>
<script>
$("#datatables-lists").DataTable({
	language: {
		"sProcessing": "处理中...",
		"sLengthMenu": "显示 _MENU_ 项结果",
		"sZeroRecords": "没有匹配结果",
		"sInfo": "显示第 _START_ 至 _END_ 项结果，共 _TOTAL_ 项",
		"sInfoEmpty": "显示第 0 至 0 项结果，共 0 项",
		"sInfoFiltered": "(由 _MAX_ 项结果过滤)",
		"sInfoPostFix": "",
		"sSearch": "搜索:",
		"sUrl": "",
		"sEmptyTable": "表中数据为空",
		"sLoadingRecords": "载入中...",
		"sInfoThousands": ",",
		"oPaginate": {
			"sFirst": "首页",
			"sPrevious": "上页",
			"sNext": "下页",
			"sLast": "末页"
		},
		"oAria": {
			"sSortAscending": ": 以升序排列此列",
			"sSortDescending": ": 以降序排列此列"
		}
	},
	destroy: true,	// 允许重建
	bProcessing:true,  // 表格数据过多处理时显示: sProcessing
	lengthMenu: [[10, 25, 50, 100, -1], [10, 25, 50, 100, "全部"]],
	order: [],
	 //scrollY: 480,	// 滚动条
	 //scrollCollapse: true,
	 //jQueryUI: true,
	 stateSave: true,	// 保存最后一次分页信息、排序信息，当页面刷新，或者重新进入这个页面，恢复上次的状态。
	 stateDuration: 86400,	// 本地储存(0~更大)还是session储存(-1) 
});
</script>
{% endblock js %}

templates/webssh/test.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>测试</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static 'asciinema-player/asciinema-player.css' %}">

  
</head>
<body>

<asciinema-player src="/media/{{ log.detail }}"></asciinema-player>

<script src="{% static 'asciinema-player/asciinema-player.js' %}"></script>
</body>
</html>