apps/batch/urls.py
from django.urls import path
from . import views


app_name = "batch"
urlpatterns = [
    path('cmd/', views.cmd, name='cmd'),
    path('script/', views.script, name='script'),
    path('file/', views.file, name='file'),
    path('playbook/', views.playbook, name='playbook'),
    path('module/', views.module, name='module'),
    path('logs/', views.logs, name='logs'),
]

devops/urls.py
# from django.contrib import admin
from django.urls import path, include, re_path
from server.views import index
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    # path('admin/', admin.site.urls),
    
    path('', index),
    
    path('server/', include('server.urls', namespace='server')),
    path('api/server/', include('server.urls_api', namespace='server_api')),
    
    path('user/', include('user.urls', namespace='user')),
    path('api/user/', include('user.urls_api', namespace='user_api')),
    
    path('webssh/', include('webssh.urls', namespace='webssh')),
    path('api/webssh/', include('webssh.urls_api', namespace='webssh_api')),

    path('webtelnet/', include('webtelnet.urls', namespace='webtelnet')),

    path('webguacamole/', include('webguacamole.urls', namespace='webguacamole')),

    path('batch/', include('batch.urls', namespace='batch')),
    path('api/batch/', include('batch.urls_api', namespace='batch_api')),

]

"""
正式部署时一般静态文件直接用 nginx 转发，django 本身处理动态请求
"""
if settings.DEBUG:  # debug 模式下加载 /media 静态资源
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if not settings.DEBUG:  # 非 debug 模式下加载 /static 静态资源，debug 模式下 django 开发服务器会默认加载静态资源
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

apps/batch/models.py
from django.db import models

# Create your models here.


class BatchCmdLog(models.Model):
    TYPE_CHOICES = (
        (1, '命令'),
        (2, '脚本'),
        (3, '上传文件'),
        (4, 'playbook'),
        (5, 'module'),
    )
    user = models.CharField(max_length=64, verbose_name='操作人')
    hosts = models.TextField(verbose_name='主机信息')
    cmd = models.TextField('命令详情/脚本', blank=True, null=True)
    type = models.SmallIntegerField(default=1, choices=TYPE_CHOICES, verbose_name='类型')
    script = models.CharField(max_length=128, blank=True, null=True, verbose_name="脚本(文件名)")
    detail = models.CharField(max_length=128, blank=True, null=True, verbose_name="结果详情(文件名)")
    address = models.GenericIPAddressField('IP地址', blank=True, null=True)
    useragent = models.CharField(max_length=512, blank=True, null=True, verbose_name='User_Agent')
    start_time = models.DateTimeField('会话开始时间')
    create_time = models.DateTimeField('事件时间', auto_now_add=True)

    def __str__(self):
        return self.user

    class Meta:
        ordering = ["-create_time"]
        verbose_name = '批量日志'
        verbose_name_plural = '批量日志'

apps/batch/views.py
from django.shortcuts import render
from util.tool import login_required
from .models import BatchCmdLog
from server.models import HostGroup
from user.models import User
from ratelimit.decorators import ratelimit      # 限速
from ratelimit import ALL
from util.rate import rate, key
# Create your views here.


@ratelimit(key=key, rate=rate, method=ALL, block=True)
@login_required
def cmd(request):
    user = User.objects.get(id=int(request.session.get('userid')))
    groups = HostGroup.objects.filter(user=user)
    return render(request, 'batch/cmd.html', locals())


@ratelimit(key=key, rate=rate, method=ALL, block=True)
@login_required
def script(request):
    user = User.objects.get(id=int(request.session.get('userid')))
    groups = HostGroup.objects.filter(user=user)
    return render(request, 'batch/script.html', locals())


@ratelimit(key=key, rate=rate, method=ALL, block=True)
@login_required
def file(request):
    user = User.objects.get(id=int(request.session.get('userid')))
    groups = HostGroup.objects.filter(user=user)
    return render(request, 'batch/file.html', locals())


@ratelimit(key=key, rate=rate, method=ALL, block=True)
@login_required
def playbook(request):
    user = User.objects.get(id=int(request.session.get('userid')))
    groups = HostGroup.objects.filter(user=user)
    return render(request, 'batch/playbook.html', locals())


@ratelimit(key=key, rate=rate, method=ALL, block=True)
@login_required
def module(request):
    user = User.objects.get(id=int(request.session.get('userid')))
    groups = HostGroup.objects.filter(user=user)
    return render(request, 'batch/module.html', locals())


@ratelimit(key=key, rate=rate, method=ALL, block=True)
@login_required
def logs(request):
    logs = BatchCmdLog.objects.all()
    return render(request, 'batch/logs.html', locals())

templates/batch/logs - 副本.html
{% extends 'base.html' %}
{% load my_tags %}
{% load static %}

  {% block css %}
  <link rel="stylesheet" href="{% static 'asciinema-player/asciinema-player.css' %}">
  <link rel="stylesheet" href="{% static 'guacamole/css/playback.css' %}">
  {% endblock css %}
  
  {% block title %}
  <title>批量日志</title>
  {% endblock title %}

	{% block navheader %}
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-1">
          <div class="col-12">
            <ol class="breadcrumb">
              <li class="breadcrumb-item">日志审计</li>
              <li class="breadcrumb-item active">批量日志</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
	{% endblock navheader %}
	
		  {% block content %}
          <div class="card content-list">
            <div class="card-header">
              <h3 class="card-title">批量日志</h3>
				<div class="card-tools">
				  <!--button type="button" class="btn btn-tool" data-widget="collapse">
					<i class="fas fa-minus"></i>
				  </button>
				  <button type="button" class="btn btn-tool" data-widget="remove">
					<i class="fas fa-times"></i>
				  </button-->
				</div>
            </div>
            <!-- /.card-header -->
            <div class="card-body table-responsive">
              <table id="datatables-lists" class="table table-bordered table-hover table-sm">
                <thead>
                <tr>
				  <th>操作人</th>
				  <th>主机信息</th>
				  <th>类型</th>
				  <th>命令/脚本</th>
				  <th>客户端IP</th>
				  <th>客户端</th>
				  <th>开始时间</th>
				  <th>结束时间</th>
				  <th>操作</th>
                </tr>
                </thead>
                <tbody>
				{% for log in logs %}
                <tr>
				  {% set lenhosts = len(log.hosts) %}
				  {% set lencmd =  len(log.cmd) %}
				  {% set lenuseragent =  len(log.useragent) %}
				  <td>{{ log.user}}</td>
				  <td>{{ log.hosts | linebreaksbr | truncatechars_html:255 }}{% if lenhosts > 255 %}<br>...{% endif %}</td>
				  
				  <td>
				  {% if log.get_type_display == '命令' %}
					<span class="badge badge-success">{{ log.get_type_display }}</span>
				  {% elif log.get_type_display == '脚本' %}
					<span class="badge badge-info">{{ log.get_type_display }}</span>
				  {% elif log.get_type_display == '上传文件' %}
					<span class="badge badge-primary">{{ log.get_type_display }}</span>
				  {% else %}
				    <span class="badge badge-secondary">{{ log.get_type_display }}</span>
				  {% endif %}
				  </td>
				  
				  <td>{{ log.cmd | linebreaksbr | truncatechars_html:45 }}{% if lencmd > 45 %}<br>...{% endif %}</td>
				  <td>{{ log.address | default:'' }}</td>
				  <td>{{ log.useragent | truncatechars_html:30 | default:'' }}{% if lenuseragent > 30 %}...{% endif %}</td>
				  <td>{{ log.start_time | date:"Y/m/d H:i:s" }}</td>
				  <td>{{ log.create_time | date:"Y/m/d H:i:s" }}</td>
				  <td>
				  {% if log.get_type_display == '命令' %}
					<a href="javascript:void(0)" class="btn btn-success btn-sm mb-1" info="{{ log.user }}-{{ log.address | default:'' }}" type="{{ log.get_type_display }}" onclick="viewcmd(this);"><cmd hidden>{{ log.cmd }}</cmd><i class="fas fa-list"></i> 命令详情</a>&nbsp;&nbsp;
				  {% elif log.get_type_display == '上传文件' %}
					<a href="javascript:void(0)" class="btn btn-secondary btn-sm mb-1" info="{{ log.user }}-{{ log.address | default:'' }}" type="{{ log.get_type_display }}" onclick="viewcmd(this);"><cmd hidden>{{ log.cmd }}</cmd><i class="fas fa-list"></i> 上传详情</a>&nbsp;&nbsp;
				  {% elif log.get_type_display == '脚本' %}
					<a href="javascript:void(0)" class="btn btn-primary btn-sm mb-1" info="{{ log.user }}-{{ log.address | default:'' }}" type="{{ log.get_type_display }}" onclick="viewcmd(this);"><cmd hidden>/media/{{ log.script }}</cmd><i class="fas fa-list"></i> 脚本详情</a>&nbsp;&nbsp;
				  {% elif log.get_type_display == 'playbook' %}
					<a href="javascript:void(0)" class="btn btn-primary btn-sm mb-1" info="{{ log.user }}-{{ log.address | default:'' }}" type="{{ log.get_type_display }}" onclick="viewcmd(this);"><cmd hidden>/media/{{ log.script }}</cmd><i class="fas fa-list"></i> playbook详情</a>&nbsp;&nbsp;
				  {% elif log.get_type_display == 'module' %}
				    <a href="javascript:void(0)" class="btn btn-primary btn-sm mb-1" info="{{ log.user }}-{{ log.address | default:'' }}" type="{{ log.get_type_display }}" onclick="viewcmd(this);"><cmd hidden>{{ log.cmd }}</cmd><i class="fas fa-list"></i> module详情</a>&nbsp;&nbsp;
				  {% endif %}
				  <a href="javascript:void(0)" class="btn btn-info btn-sm mb-1" id="{{ log.detail }}" info="{{ log.user }}-{{ log.address | default:'' }}" onclick="viewsshvideo(this);"><i class="fas fa-video"></i> 回放</a>
				  </td>
                </tr>
				{% endfor %}
                </tbody>
                <tfoot>
                <tr>
				  <th>操作人</th>
				  <th>主机信息</th>
				  <th>类型</th>
				  <th>命令/脚本</th>
				  <th>客户端IP</th>
				  <th>客户端</th>
				  <th>开始时间</th>
				  <th>结束时间</th>
				  <th>操作</th>
                </tr>
                </tfoot>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card --> 
		  
		  	<!--查看命令详情框-->
			<style>
			#view_cmd_container {
				overflow:hidden;
			}
			</style>
			<div id="modal-view-cmd" class="iziModal">
				<div class="card-body">
				  <div class="row">
					  <div class="col-10"><h5 class="mb-3" id="view_cmd_info">命令</h5></div>
					  <div class="col-2"><a href="javascript:void(0)" class="iziModal-button-close float-right" data-izimodal-close="" style="color:black;vertical-align:middle"><i class="fas fa-times fa-lg"></i></a></div>
					  <div class="col-12" id="view_cmd_container">demo</div>
				  </div>
				</div>
			</div>
			
		  	<!--查看录像框-->
			<div id="modal-view" class="iziModal">
				<div class="card-body">
				  <div class="row">
					  <div class="col-10"><h5 class="mb-3" id="view_info">回放</h5></div>
					  <div class="col-2"><a href="javascript:void(0)" class="iziModal-button-close float-right" data-izimodal-close="" style="color:black;vertical-align:middle"><i class="fas fa-times fa-lg"></i></a></div>
					  <div class="col-12" id="view_container"><asciinema-player src="/media/demo.txt" theme="monokai" title="demo" rows="250"></asciinema-player></div>
					  <div class="col-12">
						<div class="alert alert-info alert-dismissible mt-2 mb-0"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>提示：如无法看清某些操作，请尝试全屏查看。</div>
					  </div>
				  </div>
				</div>
			</div>
		  
		  {% endblock content %}

{% block js %}
<!-- DataTables -->
<script src="{% static 'adminlte/plugins/datatables/jquery.dataTables.js' %}"></script>
<script src="{% static 'adminlte/plugins/datatables/dataTables.bootstrap4.js' %}"></script>
<script>
	$("#datatables-lists").DataTable({
		language: {
			"sProcessing": "处理中...",
			"sLengthMenu": "显示 _MENU_ 项结果",
			"sZeroRecords": "没有匹配结果",
			"sInfo": "显示第 _START_ 至 _END_ 项结果，共 _TOTAL_ 项",
			"sInfoEmpty": "显示第 0 至 0 项结果，共 0 项",
			"sInfoFiltered": "(由 _MAX_ 项结果过滤)",
			"sInfoPostFix": "",
			"sSearch": "搜索:",
			"sUrl": "",
			"sEmptyTable": "无数据",
			"sLoadingRecords": "载入中...",
			"sInfoThousands": ",",
			"oPaginate": {
				"sFirst": "首页",
				"sPrevious": "上页",
				"sNext": "下页",
				"sLast": "末页"
			},
			"oAria": {
				"sSortAscending": ": 以升序排列此列",
				"sSortDescending": ": 以降序排列此列"
			}
		},
		destroy: true,	// 允许重建
		bProcessing:true,  // 表格数据过多处理时显示: sProcessing
		lengthMenu: [[5, 10, 25, 50, 100, -1], [5, 10, 25, 50, 100, "全部"]],
		columnDefs : [ { targets : 8, "orderable" : false } ],
		order: [],
		 //scrollY: 480,	// 滚动条
		 //scrollCollapse: true,
		 //jQueryUI: true,
		 stateSave: true,	// 保存最后一次分页信息、排序信息，当页面刷新，或者重新进入这个页面，恢复上次的状态。
		 stateDuration: 86400,	// 本地储存(0~更大)还是session储存(-1) 
	});
</script>

<script src="{% static 'asciinema-player/asciinema-player.js' %}"></script>

<!-- ace 编辑器 -->
<script src="{% static 'ace-new/src-min-noconflict/ace.js' %}"></script>
<script src="{% static 'ace-new/src-min-noconflict/ext-language_tools.js' %}"></script>

<!-- Guacamole JavaScript API -->
<script src="{% static 'guacamole/js/all.min.js' %}"></script>
<script src="{% static 'guacamole/js/playback.js' %}"></script>

<script>

	viewcmd = function(event) {
		var thisObj = $(event);	//js对象转jquery对象
		var info = thisObj.attr('info');
		var type = thisObj.attr('type');
		var cmd = thisObj.find('cmd').text();
		if (type == "命令") {
			$("#view_cmd_info").text("命令详情：" + info);
		} else if (type == "脚本") {
			$("#view_cmd_info").text("脚本详情：" + info);
			var htmlobj= $.ajax({url:cmd,async:false});
			if (htmlobj.status > 399) {
				cmd = "获取脚本错误！"
			} else {
				cmd = htmlobj.responseText;
			};
		} else if (type == "上传文件") {
			$("#view_cmd_info").text("上传详情：" + info);
		} else if (type == "playbook") {
			$("#view_cmd_info").text("playbook详情：" + info);
			var htmlobj= $.ajax({url:cmd,async:false});
			if (htmlobj.status > 399) {
				cmd = "获取playbook错误！"
			} else {
				cmd = htmlobj.responseText;
			};
		} else if (type == "module") {
			$("#view_cmd_info").text("module详情：" + info);
		};

		//$("#view_cmd_container").text(cmd);
		$("#modal-view-cmd").iziModal({
			iconClass: 'icon-announcement',
			width: 1080,
			overlayClose: false,	// 是否允许点击模态窗口的外部来关闭模态窗口。
			closeOnEscape: false, 	// 是否允许通过点击ESC键来关闭模态窗口。
		});
		$('#modal-view-cmd').iziModal('open');
		
		ace.require("ace/ext/language_tools");
		let editor = ace.edit("view_cmd_container", {
			theme: "ace/theme/tomorrow_night_eighties",
			mode: "ace/mode/sh",
			autoScrollEditorIntoView: true,
			maxLines: 30,
			minLines: 20,
		});
		editor.setShowPrintMargin(false);
		editor.setReadOnly(true);
		editor.setValue(cmd, -1);
	};
	
	$(document).on('closed', '#modal-view-cmd', function (e) {
		let editor = ace.edit("view_cmd_container");
		editor.destroy();
		$('#modal-view-cmd').iziModal('destroy');	//销毁模态窗口。
	});
	
	
	viewsshvideo = function(event) {
		var thisObj = $(event);	//js对象转jquery对象
		// var info = thisObj.attr('id').split("-")[0];
		var info = thisObj.attr('info');
		var file = thisObj.attr("id");
		$("#view_info").text("回放：" + info);
		//var res = '<asciinema-player src="/media/' + file + '" theme="monokai" title="' + info + '" rows="30" idle-time-limit="1"></asciinema-player>';
		var res = '<asciinema-player src="/media/' + file + '" theme="monokai" title="' + info + '" rows="45" cols="250"></asciinema-player>';
		$("#view_container").html(res);
		$("#modal-view").iziModal({
			iconClass: 'icon-announcement',
			width: 1080,
			overlayClose: false,	// 是否允许点击模态窗口的外部来关闭模态窗口。
			closeOnEscape: false, 	// 是否允许通过点击ESC键来关闭模态窗口。
		});
		$('#modal-view').iziModal('open');
	};
	
	$(document).on('closed', '#modal-view', function (e) {
		$('#modal-view').iziModal('destroy');	//销毁模态窗口。
	});

</script>
{% endblock js %}

templates/batch/logs.html
{% extends 'base.html' %}
{% load my_tags %}
{% load static %}

  {% block css %}
  <link rel="stylesheet" href="{% static 'asciinema-player/asciinema-player.css' %}">
  <link rel="stylesheet" href="{% static 'guacamole/css/playback.css' %}">
  {% endblock css %}
  
  {% block title %}
  <title>批量日志</title>
  {% endblock title %}

	{% block navheader %}
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-1">
          <div class="col-12">
            <ol class="breadcrumb">
              <li class="breadcrumb-item">日志审计</li>
              <li class="breadcrumb-item active">批量日志</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
	{% endblock navheader %}
	
		  {% block content %}
          <div class="card content-list">
            <div class="card-header">
              <h3 class="card-title">批量日志</h3>
				<div class="card-tools">
				  <!--button type="button" class="btn btn-tool" data-widget="collapse">
					<i class="fas fa-minus"></i>
				  </button>
				  <button type="button" class="btn btn-tool" data-widget="remove">
					<i class="fas fa-times"></i>
				  </button-->
				</div>
            </div>
            <!-- /.card-header -->
            <div class="card-body table-responsive">
              <table id="datatables-lists" class="table table-bordered table-hover table-sm">
                <thead>
                <tr>
				  <th>操作人</th>
				  <th>主机信息</th>
				  <th>类型</th>
				  <th>命令/脚本</th>
				  <th>客户端IP</th>
				  <th>客户端</th>
				  <th>开始时间</th>
				  <th>结束时间</th>
				  <th>操作</th>
                </tr>
                </thead>
				
                <!--tbody>
				dataTables 服务器端处理模式
                </tbody-->
				
                <tfoot>
                <tr>
				  <th>操作人</th>
				  <th>主机信息</th>
				  <th>类型</th>
				  <th>命令/脚本</th>
				  <th>客户端IP</th>
				  <th>客户端</th>
				  <th>开始时间</th>
				  <th>结束时间</th>
				  <th>操作</th>
                </tr>
                </tfoot>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card --> 
		  
		  	<!--查看命令详情框-->
			<style>
			#view_cmd_container {
				overflow:hidden;
			}
			</style>
			<div id="modal-view-cmd" class="iziModal">
				<div class="card-body">
				  <div class="row">
					  <div class="col-10"><h5 class="mb-3" id="view_cmd_info">命令</h5></div>
					  <div class="col-2"><a href="javascript:void(0)" class="iziModal-button-close float-right" data-izimodal-close="" style="color:black;vertical-align:middle"><i class="fas fa-times fa-lg"></i></a></div>
					  <div class="col-12" id="view_cmd_container">demo</div>
				  </div>
				</div>
			</div>
			
		  	<!--查看录像框-->
			<div id="modal-view" class="iziModal">
				<div class="card-body">
				  <div class="row">
					  <div class="col-10"><h5 class="mb-3" id="view_info">回放</h5></div>
					  <div class="col-2"><a href="javascript:void(0)" class="iziModal-button-close float-right" data-izimodal-close="" style="color:black;vertical-align:middle"><i class="fas fa-times fa-lg"></i></a></div>
					  <div class="col-12" id="view_container"><asciinema-player src="/media/demo.txt" theme="monokai" title="demo" rows="250"></asciinema-player></div>
					  <div class="col-12">
						<div class="alert alert-info alert-dismissible mt-2 mb-0"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>提示：如无法看清某些操作，请尝试全屏查看。</div>
					  </div>
				  </div>
				</div>
			</div>
		  
		  {% endblock content %}

{% block js %}
<!-- DataTables -->
<script src="{% static 'adminlte/plugins/datatables/jquery.dataTables.js' %}"></script>
<script src="{% static 'adminlte/plugins/datatables/dataTables.bootstrap4.js' %}"></script>
<script>
	// $.fn.dataTable.ext.errMode = 'throw';
	$.fn.dataTable.ext.errMode = function( settings, tn, msg){
		//打印msg，和tn来判断，进了这个方法都是ajax走了error才会到这里来
		console.log(settings);
		console.log(tn);
		console.log(msg);
	};
	$("#datatables-lists").DataTable({
		language: {
			"sProcessing": "加载中...",
			"sLengthMenu": "显示 _MENU_ 项结果",
			"sZeroRecords": "没有匹配结果",
			"sInfo": "显示第 _START_ 至 _END_ 项结果，共 _TOTAL_ 项",
			"sInfoEmpty": "显示第 0 至 0 项结果，共 0 项",
			"sInfoFiltered": "(由 _MAX_ 项结果过滤)",
			"sInfoPostFix": "",
			"sSearch": "搜索:",
			"sUrl": "",
			"sEmptyTable": "无数据",
			"sLoadingRecords": "载入中...",
			"sInfoThousands": ",",
			"oPaginate": {
				"sFirst": "首页",
				"sPrevious": "上页",
				"sNext": "下页",
				"sLast": "末页"
			},
			"oAria": {
				"sSortAscending": ": 以升序排列此列",
				"sSortDescending": ": 以降序排列此列"
			}
		},
		destroy: true,	// 允许重建
		bProcessing:true,  // 表格数据过多处理时显示: sProcessing
		// lengthMenu: [[5, 10, 25, 50, 100, -1], [5, 10, 25, 50, 100, "全部"]],
		lengthMenu: [[5, 10, 25, 50, 100], [5, 10, 25, 50, 100]],
		columnDefs : [ { targets : 8, "orderable" : false } ],
		order: [],
		 //scrollY: 480,	// 滚动条
		 //scrollCollapse: true,
		 //jQueryUI: true,
		 stateSave: true,	// 保存最后一次分页信息、排序信息，当页面刷新，或者重新进入这个页面，恢复上次的状态。
		 stateDuration: 86400,	// 本地储存(0~更大)还是session储存(-1)
		 
		 processing: true,
		 serverSide: true,	// 开启服务器端处理模式
		 ajax: {
			url: '{% url "batch_api:logs" %}',
			type: 'POST',
			data: {
				csrfmiddlewaretoken: '{{ request.COOKIES.csrftoken }}',
			}
		 },
	});
</script>

<script src="{% static 'asciinema-player/asciinema-player.js' %}"></script>

<!-- ace 编辑器 -->
<script src="{% static 'ace-new/src-min-noconflict/ace.js' %}"></script>
<script src="{% static 'ace-new/src-min-noconflict/ext-language_tools.js' %}"></script>

<!-- Guacamole JavaScript API -->
<script src="{% static 'guacamole/js/all.min.js' %}"></script>
<script src="{% static 'guacamole/js/playback.js' %}"></script>

<script>

	viewcmd = function(event) {
		var thisObj = $(event);	//js对象转jquery对象
		var info = thisObj.attr('info');
		var type = thisObj.attr('type');
		var cmd = thisObj.find('cmd').text();
		if (type == "命令") {
			$("#view_cmd_info").text("命令详情：" + info);
		} else if (type == "脚本") {
			$("#view_cmd_info").text("脚本详情：" + info);
			var htmlobj= $.ajax({url:cmd,async:false});
			if (htmlobj.status > 399) {
				cmd = "获取脚本错误！"
			} else {
				cmd = htmlobj.responseText;
			};
		} else if (type == "上传文件") {
			$("#view_cmd_info").text("上传详情：" + info);
		} else if (type == "playbook") {
			$("#view_cmd_info").text("playbook详情：" + info);
			var htmlobj= $.ajax({url:cmd,async:false});
			if (htmlobj.status > 399) {
				cmd = "获取playbook错误！"
			} else {
				cmd = htmlobj.responseText;
			};
		} else if (type == "module") {
			$("#view_cmd_info").text("module详情：" + info);
		};

		//$("#view_cmd_container").text(cmd);
		$("#modal-view-cmd").iziModal({
			iconClass: 'icon-announcement',
			width: 1080,
			overlayClose: false,	// 是否允许点击模态窗口的外部来关闭模态窗口。
			closeOnEscape: false, 	// 是否允许通过点击ESC键来关闭模态窗口。
		});
		$('#modal-view-cmd').iziModal('open');
		
		ace.require("ace/ext/language_tools");
		let editor = ace.edit("view_cmd_container", {
			theme: "ace/theme/tomorrow_night_eighties",
			mode: "ace/mode/sh",
			autoScrollEditorIntoView: true,
			maxLines: 30,
			minLines: 20,
		});
		editor.setShowPrintMargin(false);
		editor.setReadOnly(true);
		editor.setValue(cmd, -1);
	};
	
	$(document).on('closed', '#modal-view-cmd', function (e) {
		let editor = ace.edit("view_cmd_container");
		editor.destroy();
		$('#modal-view-cmd').iziModal('destroy');	//销毁模态窗口。
	});
	
	
	viewsshvideo = function(event) {
		var thisObj = $(event);	//js对象转jquery对象
		// var info = thisObj.attr('id').split("-")[0];
		var info = thisObj.attr('info');
		var file = thisObj.attr("id");
		$("#view_info").text("回放：" + info);
		//var res = '<asciinema-player src="/media/' + file + '" theme="monokai" title="' + info + '" rows="30" idle-time-limit="1"></asciinema-player>';
		var res = '<asciinema-player src="/media/' + file + '" theme="monokai" title="' + info + '" rows="45" cols="250"></asciinema-player>';
		$("#view_container").html(res);
		$("#modal-view").iziModal({
			iconClass: 'icon-announcement',
			width: 1080,
			overlayClose: false,	// 是否允许点击模态窗口的外部来关闭模态窗口。
			closeOnEscape: false, 	// 是否允许通过点击ESC键来关闭模态窗口。
		});
		$('#modal-view').iziModal('open');
	};
	
	$(document).on('closed', '#modal-view', function (e) {
		$('#modal-view').iziModal('destroy');	//销毁模态窗口。
	});

</script>
{% endblock js %}