apps/server/urls.py
from django.urls import path
from . import views

app_name = "server"
urlpatterns = [
    path('', views.index, name='index'),
    path('hosts/', views.hosts, name='hosts'),
    path('host/<int:host_id>/', views.host, name='host'),
    path('host/<int:host_id>/edit/', views.host_edit, name='host_edit'),
    path('host/add/', views.host_add, name='host_add'),

    path('users/', views.users, name='users'),
    path('user/<int:user_id>/', views.user, name='user'),
    path('user/<int:user_id>/edit/', views.user_edit, name='user_edit'),
    path('user/add/', views.user_add, name='user_add'),

    path('groups/', views.groups, name='groups'),
    path('group/<int:group_id>/', views.group, name='group'),
    path('group/<int:group_id>/edit/', views.group_edit, name='group_edit'),
    path('group/add/', views.group_add, name='group_add'),

]

apps/user/urls.py
from django.urls import path
from . import views


app_name = "user"
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('lockscreen/', views.lockscreen, name='lockscreen'),
    path('users/', views.users, name='users'),
    path('groups/', views.groups, name='groups'),
    path('logs/', views.logs, name='logs'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.profile_edit, name='profile_edit'),
    path('user/<int:user_id>/', views.user, name='user'),
    path('user/<int:user_id>/edit/', views.user_edit, name='user_edit'),
    path('user/add/', views.user_add, name='user_add'),
    
    path('group/<int:group_id>/', views.group, name='group'),
    path('group/<int:group_id>/edit/', views.group_edit, name='group_edit'),
    path('group/add/', views.group_add, name='group_add'),
    
]

apps/webssh/urls.py
from django.urls import path
from . import views


app_name = "webssh"
urlpatterns = [
    path('hosts/', views.hosts, name='hosts'),
    path('terminal/', views.terminal, name='terminal'),
    path('terminal/cli/', views.terminal_cli, name='terminal_cli'),
    path('terminal/cli/sftp', views.terminal_cli_sftp, name='terminal_cli_sftp'),
    path('terminal/view/', views.terminal_view, name='terminal_view'),
    path('terminal/clissh/view/', views.terminal_clissh_view, name='terminal_clissh_view'),
    path('logs/', views.logs, name='logs'),
    path('sessions/', views.sessions, name='sessions'),
]

devops/urls.py
# from django.contrib import admin
from django.urls import path, include, re_path
from server.views import index
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    # path('admin/', admin.site.urls),
    
    path('', index),
    
    path('server/', include('server.urls', namespace='server')),
    path('api/server/', include('server.urls_api', namespace='server_api')),
    
    path('user/', include('user.urls', namespace='user')),
    path('api/user/', include('user.urls_api', namespace='user_api')),
    
    path('webssh/', include('webssh.urls', namespace='webssh')),
    path('api/webssh/', include('webssh.urls_api', namespace='webssh_api')),

    path('webtelnet/', include('webtelnet.urls', namespace='webtelnet')),

    path('webguacamole/', include('webguacamole.urls', namespace='webguacamole')),

    path('batch/', include('batch.urls', namespace='batch')),
    path('api/batch/', include('batch.urls_api', namespace='batch_api')),

]

"""
正式部署时一般静态文件直接用 nginx 转发，django 本身处理动态请求
"""
if settings.DEBUG:  # debug 模式下加载 /media 静态资源
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if not settings.DEBUG:  # 非 debug 模式下加载 /static 静态资源，debug 模式下 django 开发服务器会默认加载静态资源
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

apps/server/models.py
from django.db import models
# Create your models here.


class HostGroup(models.Model):
    group_name = models.CharField(max_length=128, verbose_name="组名")
    # 用户删除时，相关的主机组也删除
    user = models.ForeignKey('user.User', on_delete=models.CASCADE, verbose_name="归属用户")
    memo = models.TextField(blank=True, null=True, verbose_name="备注")
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')

    def __str__(self):
        return self.group_name

    class Meta:
        ordering = ["-create_time"]
        verbose_name = '主机组'
        verbose_name_plural = "主机组"
        unique_together = ('group_name', 'user')  # 同一用户下，主机组必须唯一


class RemoteUser(models.Model):
    """
    名称唯一，用户名可以重复，不同主机登陆用户名相同，密码不同
    """
    name = models.CharField(unique=True, max_length=128, verbose_name="名称")
    username = models.CharField(max_length=128, verbose_name="用户名")
    password = models.CharField(max_length=512, verbose_name="密码")
    enabled = models.BooleanField(default=False, verbose_name='登陆后是否su跳转超级用户')
    superusername = models.CharField(max_length=128, blank=True, null=True, verbose_name="超级用户")
    superpassword = models.CharField(max_length=512, blank=True, null=True, verbose_name="超级密码")
    memo = models.TextField(blank=True, null=True, verbose_name='备注')
    create_time = models.DateTimeField('添加时间', auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["-create_time"]
        verbose_name = "主机账户"
        verbose_name_plural = "主机账户"


class RemoteUserBindHost(models.Model):
    PROTOCOL_CHOICES = (    # 目前支持ssh, telnet
        (1, 'ssh'),
        (2, 'telnet'),
        (3, 'rdp'),
        (4, 'vnc'),
        (5, 'sftp'),
        (6, 'ftp'),
    )
    TYPE_CHOICES = (
        (1, '服务器'),
        (2, '防火墙'),
        (3, '路由器'),
        (4, '二层交换机'),
        (5, '三层交换机'),
        (6, '虚拟机'),
        (7, 'PC机'),
    )
    ENV_CHOICES = (
        (1, '正式环境'),
        (2, '测试环境'),
    )
    PLATFORM_CHOICES = (
        (1, 'linux'),
        (2, 'windows'),
        (3, 'unix'),
    )
    hostname = models.CharField(max_length=128, unique=True, verbose_name='主机名')
    type = models.SmallIntegerField(default=1, choices=TYPE_CHOICES, verbose_name='类型')
    ip = models.GenericIPAddressField(verbose_name='主机IP')  # 做了ip映射，ip可能重复，ip:port 不会重复
    wip = models.GenericIPAddressField(verbose_name='公网IP', blank=True, null=True)
    protocol = models.SmallIntegerField(default=1, choices=PROTOCOL_CHOICES, verbose_name='协议')
    env = models.SmallIntegerField(default=1, choices=ENV_CHOICES, verbose_name='环境')
    host_group = models.ManyToManyField('HostGroup', blank=True, verbose_name="主机组")
    port = models.SmallIntegerField(default=22, verbose_name='端口')
    release = models.CharField(max_length=255, default='CentOS', verbose_name='系统/型号')
    platform = models.SmallIntegerField(default=1, choices=PLATFORM_CHOICES, verbose_name='平台')
    memo = models.TextField(blank=True, null=True, verbose_name='备注')
    # on_delete 当 RemoteUser 记录被删时，阻止其操作
    remote_user = models.ForeignKey('RemoteUser', blank=True, null=True, on_delete=models.PROTECT)
    enabled = models.BooleanField(default=True, verbose_name='是否启用')
    create_time = models.DateTimeField('添加时间', auto_now_add=True)

    def __str__(self):
        return self.hostname

    class Meta:
        ordering = ["-create_time"]
        verbose_name = '远程主机'
        verbose_name_plural = '远程主机'
        unique_together = ('ip', 'protocol', 'port', 'remote_user')
        # 一个用户下，只能绑定同一个主机一次，不能一个用户下绑定两个相同主机


class ServerDetail(models.Model):
    # 远程主机删除此，serverdetail 相关数据也删除
    server = models.OneToOneField('RemoteUserBindHost', on_delete=models.CASCADE)
    cpu_model = models.CharField(max_length=128, blank=True, null=True, verbose_name='CPU型号')
    cpu_number = models.SmallIntegerField(blank=True, null=True, verbose_name='物理CPU个数')
    vcpu_number = models.SmallIntegerField(blank=True, null=True, verbose_name='逻辑CPU个数')
    disk_total = models.CharField(max_length=16, blank=True, null=True, verbose_name='磁盘空间')
    ram_total = models.SmallIntegerField(blank=True, null=True, verbose_name='内存容量')
    swap_total = models.SmallIntegerField(blank=True, null=True, verbose_name='交换空间容量')
    kernel = models.CharField(max_length=128, blank=True, null=True, verbose_name='内核版本')
    system = models.CharField(max_length=128, blank=True, null=True, verbose_name='操作系统')
    filesystems = models.TextField(blank=True, null=True, verbose_name='文件系统')
    interfaces = models.TextField(blank=True, null=True, verbose_name='网卡信息')
    server_model = models.CharField(max_length=128, blank=True, null=True, verbose_name='型号')

    class Meta:
        verbose_name = '主机详细'
        verbose_name_plural = '主机详细'

apps/server/views.py
from django.shortcuts import render, get_object_or_404
from util.tool import login_required
from .models import RemoteUserBindHost, RemoteUser, HostGroup
from user.models import User, Group
from webssh.models import TerminalSession
from django.db.models import Q
from ratelimit.decorators import ratelimit      # 限速
from ratelimit import ALL
from util.rate import rate, key
import json
# Create your views here.


@ratelimit(key=key, rate=rate, method=ALL, block=True)
@login_required
def index(request):
    if request.session['issuperuser'] and request.session['username'] == 'admin':
        host_count = RemoteUserBindHost.objects.all().count()
        user_count = User.objects.all().count()
        group_count = Group.objects.all().count()
        session_count = TerminalSession.objects.all().count()
    else:
        host_count = RemoteUserBindHost.objects.filter(
            Q(user__username=request.session['username']) | Q(group__user__username=request.session['username'])
        ).distinct().count()
        user_count = User.objects.all().count()
        group_count = Group.objects.all().count()
        session_count = TerminalSession.objects.filter(user=request.session['username']).count()
    return render(request, 'server/index.html', locals())


@ratelimit(key=key, rate=rate, method=ALL, block=True)
@login_required
def hosts(request):
    if request.session['issuperuser'] and request.session['username'] == 'admin':
        hosts = RemoteUserBindHost.objects.all()
    else:
        hosts = RemoteUserBindHost.objects.filter(
            Q(user__username=request.session['username']) | Q(group__user__username=request.session['username'])
        ).distinct()
    return render(request, 'server/hosts.html', locals())


@ratelimit(key=key, rate=rate, method=ALL, block=True)
@login_required
def host(request, host_id):
    if request.session['issuperuser'] and request.session['username'] == 'admin':
        host = get_object_or_404(
            RemoteUserBindHost,
            pk=host_id,
        )
    else:
        host = get_object_or_404(
            RemoteUserBindHost,
            Q(user__username=request.session['username']) | Q(group__user__username=request.session['username']),
            pk=host_id
        )
    try:
        host.serverdetail.filesystems = json.loads(host.serverdetail.filesystems)
        host.serverdetail.interfaces = json.loads(host.serverdetail.interfaces)
    except Exception:
        pass
    return render(request, 'server/host.html', locals())


@ratelimit(key=key, rate=rate, method=ALL, block=True)
@login_required
def host_edit(request, host_id):
    protocol_choices = (
        (1, 'ssh'),
        (2, 'telnet'),
        (3, 'rdp'),
        (4, 'vnc'),
        (5, 'sftp'),
        (6, 'ftp'),
    )
    type_choices = (
        (1, '服务器'),
        (2, '防火墙'),
        (3, '路由器'),
        (4, '二层交换机'),
        (5, '三层交换机'),
        (6, '虚拟机'),
        (7, 'PC机'),
    )
    env_choices = (
        (1, '正式环境'),
        (2, '测试环境'),
    )

    platform_choices = (
        (1, 'linux'),
        (2, 'windows'),
        (3, 'unix'),
    )
    if request.session['issuperuser'] and request.session['username'] == 'admin':
        host = get_object_or_404(
            RemoteUserBindHost,
            pk=host_id
        )
    else:
        host = get_object_or_404(
            RemoteUserBindHost,
            Q(user__username=request.session['username']) | Q(group__user__username=request.session['username']),
            pk=host_id
        )
    other_users = RemoteUser.objects.exclude(pk=host.remote_user.id).exclude(
        remoteuserbindhost__ip=host.ip,
        remoteuserbindhost__protocol=host.protocol,
        remoteuserbindhost__port=host.port,
    )
    return render(request, 'server/host_edit.html', locals())


@ratelimit(key=key, rate=rate, method=ALL, block=True)
@login_required
def host_add(request):
    protocol_choices = (
        (1, 'ssh'),
        (2, 'telnet'),
        (3, 'rdp'),
        (4, 'vnc'),
        (5, 'sftp'),
        (6, 'ftp'),
    )
    type_choices = (
        (1, '服务器'),
        (2, '防火墙'),
        (3, '路由器'),
        (4, '二层交换机'),
        (5, '三层交换机'),
        (6, '虚拟机'),
        (7, 'PC机'),
    )
    env_choices = (
        (1, '正式环境'),
        (2, '测试环境'),
    )

    platform_choices = (
        (1, 'linux'),
        (2, 'windows'),
        (3, 'unix'),
    )

    all_users = RemoteUser.objects.all()
    return render(request, 'server/host_add.html', locals())


@ratelimit(key=key, rate=rate, method=ALL, block=True)
@login_required
def users(request):
    users = RemoteUser.objects.all()
    return render(request, 'server/users.html', locals())


@ratelimit(key=key, rate=rate, method=ALL, block=True)
@login_required
def user(request, user_id):
    user = get_object_or_404(RemoteUser, pk=user_id)
    return render(request, 'server/user.html', locals())


@ratelimit(key=key, rate=rate, method=ALL, block=True)
@login_required
def user_edit(request, user_id):
    user = get_object_or_404(RemoteUser, pk=user_id)
    return render(request, 'server/user_edit.html', locals())


@ratelimit(key=key, rate=rate, method=ALL, block=True)
@login_required
def user_add(request):
    return render(request, 'server/user_add.html')


@ratelimit(key=key, rate=rate, method=ALL, block=True)
@login_required
def groups(request):
    user = User.objects.get(id=int(request.session.get('userid')))
    groups = HostGroup.objects.filter(user=user)
    for group in groups:
        if request.session['issuperuser'] and request.session['username'] == 'admin':
            group.hosts = RemoteUserBindHost.objects.filter(
                Q(host_group__id=group.id),
                enabled=True
            ).distinct()
        else:
            group.hosts = RemoteUserBindHost.objects.filter(
                Q(user__username=request.session['username']) | Q(group__user__username=request.session['username']),
                Q(host_group__id=group.id),
                enabled=True
            ).distinct()

    return render(request, 'server/groups.html', locals())


@ratelimit(key=key, rate=rate, method=ALL, block=True)
@login_required
def group(request, group_id):
    user = User.objects.get(id=int(request.session.get('userid')))
    group = get_object_or_404(HostGroup, pk=group_id, user=user)
    if request.session['issuperuser'] and request.session['username'] == 'admin':
        group.hosts = RemoteUserBindHost.objects.filter(
            Q(host_group__id=group.id),
            enabled=True
        ).distinct()
    else:
        group.hosts = RemoteUserBindHost.objects.filter(
            Q(user__username=request.session['username']) | Q(group__user__username=request.session['username']),
            Q(host_group__id=group.id),
            enabled=True
        ).distinct()
    return render(request, 'server/group.html', locals())


@ratelimit(key=key, rate=rate, method=ALL, block=True)
@login_required
def group_edit(request, group_id):
    user = User.objects.get(id=int(request.session.get('userid')))
    group = get_object_or_404(HostGroup, pk=group_id, user=user)
    if request.session['issuperuser'] and request.session['username'] == 'admin':
        group.hosts = RemoteUserBindHost.objects.filter(
            Q(host_group__id=group.id),
            enabled=True
        ).distinct()
    else:
        group.hosts = RemoteUserBindHost.objects.filter(
            Q(user__username=request.session['username']) | Q(group__user__username=request.session['username']),
            Q(host_group__id=group.id),
            enabled=True
        ).distinct()
    if request.session['issuperuser'] and request.session['username'] == 'admin':
        other_hosts = RemoteUserBindHost.objects.filter(
            ~Q(host_group__id=group_id),
            enabled=True
        ).distinct()
    else:
        other_hosts = RemoteUserBindHost.objects.filter(
            Q(user__username=request.session['username']) | Q(group__user__username=request.session['username']),
            ~Q(host_group__id=group_id),
            enabled=True
        ).distinct()
    return render(request, 'server/group_edit.html', locals())


@ratelimit(key=key, rate=rate, method=ALL, block=True)
@login_required
def group_add(request):
    if request.session['issuperuser'] and request.session['username'] == 'admin':
        all_hosts = RemoteUserBindHost.objects.filter(enabled=True)
    else:
        all_hosts = RemoteUserBindHost.objects.filter(
            Q(user__username=request.session['username']) | Q(group__user__username=request.session['username']),
            enabled=True
        ).distinct()
    return render(request, 'server/group_add.html', locals())

templates/server/index.html
{% extends 'base.html' %}
{% load static %}
{% load server_tags %}
{% load user_tags %}

  {% block title %}
  <title>运维管理系统</title>
  {% endblock title %}
		  
    {% block navheader %}
	
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-1">
          <div class="col-12">
            <ol class="breadcrumb">
              <li class="breadcrumb-item active"><h4 class="mb-0">仪表盘</h4></li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
	{% endblock navheader %}


		  {% block content %}
		  <div class="row">
			  <div class="col-lg-3 col-6 content-list">
			    {% if request|has_permission:'主机' %}
				<div class="small-box bg-info">
				  <div class="inner">
					<h3>{{ host_count }}</h3>
					<p>主机</p>
				  </div>
				  <div class="icon">
					<i class="fas fa-server"></i>
				  </div>
				  <a href="{% url 'server:hosts' %}" class="small-box-footer">查看更多 <i class="fas fa-arrow-circle-right"></i></a>
				</div>
				{% endif %}
			  </div>

			  <div class="col-lg-3 col-6 content-list">
				{% if request|has_permission:'用户' %}
				<div class="small-box bg-success">
				  <div class="inner">
					<h3>{{ user_count }}</h3>
					<p>用户</p>
				  </div>
				  <div class="icon">
					<i class="fas fa-user"></i>
				  </div>
				  <a href="{% url 'user:users' %}" class="small-box-footer">查看更多 <i class="fas fa-arrow-circle-right"></i></a>
				</div>
				{% endif %}
			  </div>

			  <div class="col-lg-3 col-6 content-list">
				{% if request|has_permission:'组' %}
				<div class="small-box bg-yellow">
				  <div class="inner">
					<h3>{{ group_count }}</h3>
					<p>用户组</p>
				  </div>
				  <div class="icon">
					<i class="fas fa-users"></i>
				  </div>
				  <a href="{% url 'user:groups' %}" class="small-box-footer">查看更多 <i class="fas fa-arrow-circle-right"></i></a>
				</div>
				{% endif %}
			  </div>

			  <div class="col-lg-3 col-6 content-list">
				{% if request|has_permission:'在线终端' %}
				<div class="small-box bg-red">
				  <div class="inner">
					<h3>{{ session_count }}</h3>
					<p>在线终端</p>
				  </div>
				  <div class="icon">
					<i class="fas fa-terminal"></i>
				  </div>
				  <a href="{% url 'webssh:sessions' %}" class="small-box-footer">查看更多 <i class="fas fa-arrow-circle-right"></i></a>
				</div>
				{% endif %}
			  </div>
			  <!-- ./col -->
			  
			  <div class="col-lg-6 col-12 content-list">
				  <div class="card">
					  <div class="card-header border-transparent">
						<h3 class="card-title">主机类型</h3>
						<!--div class="card-tools">
						  <button type="button" class="btn btn-tool" data-widget="collapse">
							<i class="fas fa-minus"></i>
						  </button>
						  <button type="button" class="btn btn-tool" data-widget="remove">
							<i class="fas fa-times"></i>
						  </button>
						</div-->
					  </div>
					  <!-- /.card-header -->
					  <div class="card-body">
						<div id="donutChart" style="max-width:100%;height:420px;"></div>
						<!-- /.table-responsive -->
					  </div>
					  <!-- /.card-body -->
					</div>
			   </div>
			  
			  <div class="col-lg-6 col-12 content-list">
				<div class="card">
				  <div class="card-header no-border">
					<h3 class="card-title">最新主机</h3>
					<!--div class="card-tools">
					  <button type="button" class="btn btn-tool" data-widget="collapse">
						<i class="fas fa-minus"></i>
					  </button>
					  <button type="button" class="btn btn-tool" data-widget="remove">
						<i class="fas fa-times"></i>
					  </button>
					</div-->
				  </div>
				  <div class="card-body p-0">
					<table class="table table-striped table-valign-middle">
					  <thead>
					  <tr>
						<th>名称</th>
						<th>IP</th>
						<th>状态</th>
						<th>添加时间</th>
					  </tr>
					  </thead>
					  <tbody>
					  
					  {% get_recent_hosts request 10 as hosts %}
					  {% for host in hosts %}
					  <tr>
						<td>{{ host.hostname }}</td>
						<td>{{ host.ip }}</td>
						<td>{% if host.enabled %}<span class="badge badge-success">启用</span>{% else %}<span class="badge badge-danger">禁用</span>{% endif %}</td>
						<td>{{ host.create_time|date:"Y/m/d H:i:s" }}</td>
					  </tr>
					  {% endfor %}
					  </tbody>
					</table>
				  </div>
				  <div class="card-footer">
					{% if request|has_permission:'主机添加' %}
				    <a class="btn btn-sm btn-success" href="{% url 'server:host_add' %}">新增主机</a>
					{% endif %}
					<a class='btn btn-info btn-sm float-right' href="{% url 'server:hosts' %}">查看所有</a>
				  </div>
				</div>
			  </div>
			  
			  
			</div>
			
		  {% endblock content %}

{% block js %}
<script src="https://cdn.bootcss.com/echarts/4.2.1/echarts.min.js"></script>
<script>
	{% get_host_types request as res %}
	
	$(function () {
	    //资产类型数量统计 饼图
        function genData() {
            let title = [];
            let type_detail = [];
			let env_detail = [];

            {% for env in res.envs %}				
				title.push("{{ env.env }}");
				env_detail.push({
					value: {{ env.total }}, 
					name: '{{ env.env }}'
				});
            {% endfor %}
			
            {% for type in res.types %}				
				title.push("{{ type.type }}");
				type_detail.push({
					value: {{ type.total }}, 
					name: '{{ type.type }}'
				});
            {% endfor %}

            return {
                title: title,
                type_detail: type_detail,
				env_detail: env_detail,
            };
        };
        // 基于准备好的dom，初始化echarts实例
        let donutChart = echarts.init(document.getElementById('donutChart'));
        let data = genData();
		// 指定图表的配置项和数据
        option = {
            title : {
                x:'center'
            },
            tooltip : {
                trigger: 'item',
                formatter: "{b} : {c} ({d}%)"
            },
            legend: {
                orient: 'vertical',
                left: 'left',
                data: data.title,
            },
            series : [
			
				{
                    name: '资产环境',
                    type: 'pie',
                    radius: [0, '42%'],
                    label: {
                        normal: {
                            position: 'inner'
                        }
                    },
                    data: data.env_detail,
                },
			
                {
                    name: '主机类型',
                    type: 'pie',
                    radius : '70%',
                    center: ['50%', '50%'],	// 位置
					roseType : 'area',	// 面积模式
					radius : ['40%', '85%'],	// 中空
                    data: data.type_detail,
                    itemStyle: {
                        emphasis: {
                            shadowBlur: 20,
                            shadowOffsetX: 10,
                            shadowColor: 'rgba(0, 0, 0, 0.5)'
                        }
                    },
					label: {
						normal: {
							show: true,
							formatter: '{b} : {c} ({d}%)',//模板变量有 {a}、{b}、{c}、{d}，分别表示系列名，数据名，数据值，百分比。{d}数据会根据value值计算百分比
						    labelLine  : {                   
								show:true
							}
						}
					}
                }
            ]
        };
		// 使用刚指定的配置项和数据显示图表。
		donutChart.setOption(option);
    });
	

</script>
{% endblock js %}