apps/server/urls.py
from django.urls import path
from . import views

app_name = "server"
urlpatterns = [
    path('', views.index, name='index'),
    path('hosts/', views.hosts, name='hosts'),
    path('host/<int:host_id>/', views.host, name='host'),
    path('host/<int:host_id>/edit/', views.host_edit, name='host_edit'),
    path('host/add/', views.host_add, name='host_add'),

    path('users/', views.users, name='users'),
    path('user/<int:user_id>/', views.user, name='user'),
    path('user/<int:user_id>/edit/', views.user_edit, name='user_edit'),
    path('user/add/', views.user_add, name='user_add'),

    path('groups/', views.groups, name='groups'),
    path('group/<int:group_id>/', views.group, name='group'),
    path('group/<int:group_id>/edit/', views.group_edit, name='group_edit'),
    path('group/add/', views.group_add, name='group_add'),

]

apps/user/urls.py
from django.urls import path
from . import views


app_name = "user"
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('lockscreen/', views.lockscreen, name='lockscreen'),
    path('users/', views.users, name='users'),
    path('groups/', views.groups, name='groups'),
    path('logs/', views.logs, name='logs'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.profile_edit, name='profile_edit'),
    path('user/<int:user_id>/', views.user, name='user'),
    path('user/<int:user_id>/edit/', views.user_edit, name='user_edit'),
    path('user/add/', views.user_add, name='user_add'),
    
    path('group/<int:group_id>/', views.group, name='group'),
    path('group/<int:group_id>/edit/', views.group_edit, name='group_edit'),
    path('group/add/', views.group_add, name='group_add'),
    
]

devops/urls.py
# from django.contrib import admin
from django.urls import path, include, re_path
from server.views import index
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    # path('admin/', admin.site.urls),
    
    path('', index),
    
    path('server/', include('server.urls', namespace='server')),
    path('api/server/', include('server.urls_api', namespace='server_api')),
    
    path('user/', include('user.urls', namespace='user')),
    path('api/user/', include('user.urls_api', namespace='user_api')),
    
    path('webssh/', include('webssh.urls', namespace='webssh')),
    path('api/webssh/', include('webssh.urls_api', namespace='webssh_api')),

    path('webtelnet/', include('webtelnet.urls', namespace='webtelnet')),

    path('webguacamole/', include('webguacamole.urls', namespace='webguacamole')),

    path('batch/', include('batch.urls', namespace='batch')),
    path('api/batch/', include('batch.urls_api', namespace='batch_api')),

]

"""
正式部署时一般静态文件直接用 nginx 转发，django 本身处理动态请求
"""
if settings.DEBUG:  # debug 模式下加载 /media 静态资源
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if not settings.DEBUG:  # 非 debug 模式下加载 /static 静态资源，debug 模式下 django 开发服务器会默认加载静态资源
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

apps/user/models.py
from django.db import models
from server.models import RemoteUserBindHost
import json
# Create your models here.


class Permission(models.Model):
    """
    权限
    """
    title = models.CharField(max_length=128, unique=True, verbose_name="标题")
    url = models.CharField(max_length=256, blank=True, null=True, verbose_name='含正则的URL')
    icon = models.CharField(max_length=128, blank=True, null=True, verbose_name='图标')
    # 如果 menu 为空，则本身就是一级菜单，比如仪表盘；不为空则是二级菜单或者按钮
    menu = models.CharField(max_length=128, blank=True, null=True, verbose_name='一级菜单')
    men_icon = models.CharField(max_length=128, blank=True, null=True, verbose_name='一级菜单图标')
    # 当为 True 时，是一个按钮，不是菜单
    is_button = models.BooleanField(default=False, verbose_name='是否为按钮')
    # 排序，菜单显示排序
    # SmallIntegerField 在使用 sqlite3 时字段为 smallint，范围从 -2^15 (-32,768) 到 2^15 - 1 (32,767) 的整型数据。
    # 存储大小为 2 个字节。unsigned 是从 0 到 65535 的整型数据。但是使用 mysql 时就变为 tinyint，范围从 -2^7 (-128) 到
    # 2^7 - 1 (123) 的整型数据。存储大小为 1 个字节。unsigned 是从 0 到 255 的整型数据。所以默认值设置大小要考虑到兼容性。
    # order = models.SmallIntegerField(default=99999, verbose_name='排序')
    order = models.SmallIntegerField(default=123, verbose_name='排序')

    def __str__(self):
        if self.menu:
            return self.menu + '-' + self.title
        return self.title

    class Meta:
        ordering = ["id"]
        verbose_name = "权限"
        verbose_name_plural = "权限"


class User(models.Model):
    SEX_CHOICES = (
        ('male', "男"),
        ('female', "女"),
    )
    ROLE_CHOICES = (
        (1, '超级管理员'),
        (2, '普通用户'),
    )
    username = models.CharField(max_length=64, unique=True, verbose_name='用户名')
    nickname = models.CharField(max_length=64, verbose_name='昵称')
    password = models.CharField(max_length=256, verbose_name='密码')
    email = models.EmailField(verbose_name='邮箱')
    sex = models.CharField(max_length=32, choices=SEX_CHOICES, default="male", verbose_name='性别')
    remote_user_bind_hosts = models.ManyToManyField(RemoteUserBindHost, blank=True, verbose_name="用户关联的远程主机")
    permission = models.ManyToManyField(Permission, blank=True, verbose_name="用户关联的权限")
    enabled = models.BooleanField(default=True, verbose_name='是否启用')
    role = models.SmallIntegerField(default=2, choices=ROLE_CHOICES, verbose_name='角色')
    groups = models.ManyToManyField('Group', blank=True, verbose_name="所属组")
    phone = models.CharField(max_length=11, blank=True, null=True, verbose_name="手机")
    weixin = models.CharField(max_length=64, blank=True, null=True, verbose_name="微信")
    qq = models.CharField(max_length=24, blank=True, null=True, verbose_name="QQ")
    setting_default = {
        'clissh': [
            {
                'name': 'securecrt',
                'path': 'C:\\Program Files\\VanDyke Software\\Clients\\SecureCRT.exe',
                'args': '/T /N "{username}@{host}-{hostname}" /SSH2 /L {login_user} /PASSWORD {login_passwd} {login_host} /P {port}',
                'enable': True
            },
            {
                'name': 'xshell',
                'path': 'C:\\Program Files (x86)\\NetSarang\\Xmanager Enterprise 5\\Xshell.exe',
                 'args': '-newtab "{username}@{host}-{hostname}" -url ssh://{login_user}:{login_passwd}@{login_host}:{port}',
                 'enable': False
            },
            {
                'name': 'putty',
                'path': 'C:\\Users\\xx\\AppData\\Roaming\\TP4A\\Teleport-Assist\\tools\\putty\\putty.exe',
                'args': '-l {login_user} -pw {login_passwd} {login_host} -P {port}',
                'enable': False
            },
            {
                'name': 'custom',
                'path': '',
                'args': '',
                'enable': False
            }
        ],
        'clisftp': [
            {
                'name': 'winscp',
                'path': 'C:\\Program Files\\winscp\\WinSCP.exe',
                'args': '/sessionname="{username}@{host}-{hostname}" {login_user}:{login_passwd}@{login_host}:{port}',
                'enable': True
            },
            {
                'name': 'custom',
                'path': '',
                'args': '',
                'enable': False
            }
        ]
    }
    setting = models.TextField(default=json.dumps(setting_default), blank=True, null=True, verbose_name="设置")
    memo = models.TextField(blank=True, null=True, verbose_name="备注")
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    last_login_time = models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')

    def __str__(self):
        return self.username

    class Meta:
        ordering = ["-create_time"]
        verbose_name = "用户"
        verbose_name_plural = "用户"


class Group(models.Model):
    group_name = models.CharField(max_length=128, unique=True, verbose_name="组名")
    remote_user_bind_hosts = models.ManyToManyField(RemoteUserBindHost, blank=True, verbose_name="组关联的远程主机")
    permission = models.ManyToManyField(Permission, blank=True, verbose_name="组关联的权限")
    memo = models.TextField(blank=True, null=True, verbose_name="备注")
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')

    def __str__(self):
        return self.group_name

    class Meta:
        ordering = ["-create_time"]
        verbose_name = "用户组"
        verbose_name_plural = "用户组"


class LoginLog(models.Model):
    event_type_choice = (
        (1, '登陆'),
        (2, '退出'),
        (3, '登陆错误'),
        (4, '修改密码失败'),
        (5, '修改密码成功'),
        (6, '添加用户'),
        (7, '删除用户'),
        (8, '添加组'),
        (9, '删除组'),
        (10, '更新用户'),
        (11, '更新组'),
        (12, '添加主机'),
        (13, '删除主机'),
        (14, '更新主机'),
        (15, '添加主机用户'),
        (16, '删除主机用户'),
        (17, '更新主机用户'),
        (18, '停止在线会话'),
        (19, '锁定在线会话'),
        (20, '解锁在线会话'),
        (21, '添加主机组'),
        (22, '删除主机组'),
        (23, '更新主机组'),
    )
    # 当用户被删除后，相关的登陆日志user字段设置为NULL
    # user = models.ForeignKey('User', blank=True, null=True, on_delete=models.PROTECT, verbose_name='用户')
    user = models.CharField(max_length=64, blank=True, null=True, verbose_name="用户")
    event_type = models.SmallIntegerField('事件类型', choices=event_type_choice, default=1)
    detail = models.TextField('事件详情', default='登陆成功')
    address = models.GenericIPAddressField('IP地址', blank=True, null=True)
    useragent = models.CharField(max_length=512, blank=True, null=True, verbose_name='User_Agent')
    create_time = models.DateTimeField('事件时间', auto_now_add=True)

    def __str__(self):
        return self.get_event_type_display()

    class Meta:
        ordering = ["-create_time"]
        verbose_name = '用户日志'
        verbose_name_plural = '用户日志'

apps/user/forms.py
from django import forms


class LoginForm(forms.Form):
    # captcha = CaptchaField(error_messages={"invalid": "验证码错误"})
    username = forms.CharField(label="用户名", min_length=1, max_length=64)
    password = forms.CharField(label="密码", min_length=6, max_length=32, widget=forms.PasswordInput)
    
    # class Meta:
    #    model = User
    #    fields = ['name', 'email', 'url', 'text', 'captcha']


class ChangePasswdForm(forms.Form):
    oldpasswd = forms.CharField(label="当前密码", min_length=6, max_length=32, widget=forms.PasswordInput)
    newpasswd = forms.CharField(label="新密码", min_length=6, max_length=32, widget=forms.PasswordInput)
    newpasswdagain = forms.CharField(label="确认新密码", min_length=6, max_length=32, widget=forms.PasswordInput)


class ChangeUserProfileForm(forms.Form):
    SEX_CHOICES = (
        ('male', "男"),
        ('female', "女"),
    )
    nickname = forms.CharField(label="昵称", max_length=64)
    email = forms.EmailField(label="邮箱")
    phone = forms.CharField(label="手机", min_length=11, max_length=11, required=False)
    weixin = forms.CharField(label="微信", max_length=64, required=False)
    qq = forms.CharField(label="QQ", max_length=64, required=False)
    sex = forms.ChoiceField(label="性别", choices=SEX_CHOICES)
    memo = forms.CharField(label="备注", max_length=256, widget=forms.Textarea, required=False)
    clissh_name = forms.CharField(label="clissh客户端", max_length=64, required=False)
    clissh_path = forms.CharField(label="clissh程序路径", max_length=512, required=False)
    clissh_args = forms.CharField(label="clissh命令参数", max_length=512, required=False)
    clisftp_name = forms.CharField(label="clisftp客户端", max_length=64, required=False)
    clisftp_path = forms.CharField(label="clisftp程序路径", max_length=512, required=False)
    clisftp_args = forms.CharField(label="clisftp命令参数", max_length=512, required=False)


class ChangeUserForm(forms.Form):
    SEX_CHOICES = (
        ('male', "男"),
        ('female', "女"),
    )
    ROLE_CHOICES = (
        (1, '超级管理员'),
        (2, '普通用户'),
    )
    userid = forms.IntegerField(label="用户ID")
    nickname = forms.CharField(label="昵称", max_length=64)
    email = forms.EmailField(label="邮箱")
    phone = forms.CharField(label="手机", min_length=11, max_length=11, required=False)
    weixin = forms.CharField(label="微信", max_length=64, required=False)
    qq = forms.CharField(label="QQ", max_length=64, required=False)
    sex = forms.ChoiceField(label="性别", choices=SEX_CHOICES)
    memo = forms.CharField(label="备注", max_length=256, widget=forms.Textarea, required=False)
    enabled = forms.BooleanField(label="是否启用", required=False)
    role = forms.ChoiceField(label="角色", choices=ROLE_CHOICES)
    groups = forms.CharField(label="用户组", max_length=102400, required=False)
    hosts = forms.CharField(label="用户拥有主机", max_length=102400, required=False)
    permissions = forms.CharField(label="用户拥有权限", max_length=102400, required=False)

    
class AddUserForm(forms.Form):
    SEX_CHOICES = (
        ('male', "男"),
        ('female', "女"),
    )
    ROLE_CHOICES = (
        (1, '超级管理员'),
        (2, '普通用户'),
    )
    username = forms.CharField(label="用户名", max_length=64)
    newpasswd = forms.CharField(label="新密码", min_length=6, max_length=32, widget=forms.PasswordInput)
    newpasswdagain = forms.CharField(label="确认新密码", min_length=6, max_length=32, widget=forms.PasswordInput)
    nickname = forms.CharField(label="昵称", max_length=64)
    email = forms.EmailField(label="邮箱")
    phone = forms.CharField(label="手机", min_length=11, max_length=11, required=False)
    weixin = forms.CharField(label="微信", max_length=64, required=False)
    qq = forms.CharField(label="QQ", max_length=64, required=False)
    sex = forms.ChoiceField(label="性别", choices=SEX_CHOICES)
    memo = forms.CharField(label="备注", max_length=256, widget=forms.Textarea, required=False)
    enabled = forms.BooleanField(label="是否启用", required=False)
    role = forms.ChoiceField(label="角色", choices=ROLE_CHOICES)
    groups = forms.CharField(label="用户组", max_length=102400, required=False)
    hosts = forms.CharField(label="用户拥有主机", max_length=102400, required=False)
    permissions = forms.CharField(label="用户拥有权限", max_length=102400, required=False)

    
class ChangeGroupForm(forms.Form):
    groupid = forms.IntegerField(label="组ID")
    memo = forms.CharField(label="备注", max_length=256, widget=forms.Textarea, required=False)
    users = forms.CharField(label="组内用户", max_length=102400, required=False)
    hosts = forms.CharField(label="组拥有主机", max_length=102400, required=False)
    permissions = forms.CharField(label="组拥有权限", max_length=102400, required=False)


class AddGroupForm(forms.Form):
    groupname = forms.CharField(label="组名", max_length=64)
    memo = forms.CharField(label="备注", max_length=256, widget=forms.Textarea, required=False)
    users = forms.CharField(label="组内用户", max_length=102400, required=False)
    hosts = forms.CharField(label="组拥有主机", max_length=102400, required=False)
    permissions = forms.CharField(label="组拥有权限", max_length=102400, required=False)

templates/user/lockscreen.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>锁定屏幕</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link href="https://cdn.bootcss.com/font-awesome/5.10.0-11/css/all.min.css" rel="stylesheet">
  
  <!-- Ionicons -->
  <link href="https://cdn.bootcss.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet">
  
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'adminlte/dist/css/adminlte.min.css' %}">
  
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  
  <style>
	/* 页面加载完后再显示，更好的显示特效 */
	body {
		display : none;
	}
  </style>
  
</head>
<body class="hold-transition lockscreen content-list">
<!-- Automatic element centering -->
<div class="lockscreen-wrapper">
  <div class="lockscreen-logo">
    运维管理系统
  </div>
  <!-- User name -->
  <div class="lockscreen-name" title="{{ request.session.username }}">{{ request.session.nickname }}</div>

  <!-- START LOCK SCREEN ITEM -->
  <div class="lockscreen-item">
    <!-- lockscreen image -->
    <div class="lockscreen-image">
      <img src="{% static 'adminlte/dist/img/timg.jpg' %}">
    </div>
    <!-- /.lockscreen-image -->

    <!-- lockscreen credentials (contains the form) -->
    <form class="lockscreen-credentials" method="post" action="{% url 'user:lockscreen' %}">
	  {% csrf_token %}
      <div class="input-group">
        <input type="password" class="form-control" name="password" placeholder="password">
        <div class="input-group-append">
          <button type="submit" class="btn"><i class="fas fa-arrow-right text-muted"></i></button>
        </div>
      </div>
    </form>
    <!-- /.lockscreen credentials -->

  </div>
  <!-- /.lockscreen-item -->
  <div class="help-block text-center">
	{% if error_message %}
		<span style="color:red;">{{ error_message }}</span>
	{% else %}
		请输入您的登陆密码解锁
	{% endif %}
  </div>
  <div class="text-center mt-2">
    <a href="{% url 'user:logout' %}">或者登陆其他用户</a>
  </div>
  <div class="lockscreen-footer text-center">
    </strong>Copyright &copy; 2019 <a href="//www.cnblogs.com/leffss" class="text-black" target="_blank">leffss</a>.</strong> All rights reserved
  </div>
</div>
<!-- /.center -->

<!-- jQuery -->
<script src="{% static 'adminlte/plugins/jquery/jquery.min.js' %}"></script>

<!-- Bootstrap 4 -->
<script src="{% static 'adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- 动画特效 -->
<script src="//cdn.bootcss.com/velocity/1.5.2/velocity.min.js"></script>
<script src="//cdn.bootcss.com/velocity/1.5.2/velocity.ui.min.js"></script>
<script>
	$(".content-list").velocity("transition.slideDownIn", { stagger: 150, drag: true });
	//$(".content-list").velocity("transition.slideRightBigIn", { stagger: 120, drag: true });	
</script>

<!-- 页面加载完后再显示，更好的显示特效 -->
<script>
	document.addEventListener("DOMContentLoaded", function(){
		$("body").css("display", "block");
	});
</script>

</body>
</html>

templates/user/user.html
{% extends 'base.html' %}
{% load static %}
{% load user_tags %}

  {% block title %}
  <title>用户详细</title>
  {% endblock title %}

  {% block css %}
  <link rel="stylesheet" href="{% static 'ztree/css/zTreeStyle/zTreeStyle.css' %}">
  {% endblock css %}
  
	{% block navheader %}
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-1">
          <div class="col-12">
            <ol class="breadcrumb">
              <li class="breadcrumb-item">用户管理</li>
			  <li class="breadcrumb-item"><a href="{% url 'user:users' %}">用户</a></li>
			  <li class="breadcrumb-item active">用户详细</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
	{% endblock navheader %}
	
		  {% block content %}
          <div class="card card-primary content-list">
            <div class="card-header">
              <h3 class="card-title">用户详细</h3>
				<div class="card-tools">
				  <a class="btn btn-tool" href="{% if request.next %}{{ request.next }}{% else %}{% url 'user:users' %}{% endif %}">返回</a>
				  
				  {% if request|has_permission:'用户编辑' %}
				  <a class="btn btn-tool" href="{% url 'user:user_edit' user.id %}?next={% if request.META.QUERY_STRING %}{{ request.META.PATH_INFO }}?{{ request.META.QUERY_STRING }}{% else %}{{ request.META.PATH_INFO }}{% endif %}" title="编辑">
					<!--i class="fas fa-wrench"></i-->编辑
				  </a>
				  {% endif %}
				  <!--button type="button" class="btn btn-tool" data-widget="collapse">
					<i class="fas fa-minus"></i>
				  </button>
				  <button type="button" class="btn btn-tool" data-widget="maximize">
				  <i class="fas fa-expand"></i>
                  </button>
				  <button type="button" class="btn btn-tool" data-widget="remove">
					<i class="fas fa-times"></i>
				  </button-->
				</div>
            </div>
            <!-- /.card-header -->
            <div class="card-body row">
				<div class="col-3 pt-1 pb-1 border-bottom">用户名：</div><div class="col-9 pt-1 pb-1 border-bottom">{{ user.username }}</div>
				<div class="col-3 pt-1 pb-1 border-bottom">昵称：</div><div class="col-9 pt-1 pb-1 border-bottom">{{ user.nickname }}</div>
				<div class="col-3 pt-1 pb-1 border-bottom">邮箱：</div><div class="col-9 pt-1 pb-1 border-bottom">{{ user.email }}</div>
				<div class="col-3 pt-1 pb-1 border-bottom">手机：</div><div class="col-9 pt-1 pb-1 border-bottom">{{ user.phone | default:'' }}</div>
				<div class="col-3 pt-1 pb-1 border-bottom">微信：</div><div class="col-9 pt-1 pb-1 border-bottom">{{ user.weixin | default:'' }}</div>
				<div class="col-3 pt-1 pb-1 border-bottom">QQ：</div><div class="col-9 pt-1 pb-1 border-bottom">{{ user.qq | default:'' }}</div>
				<div class="col-3 pt-1 pb-1 border-bottom">性别：</div><div class="col-9 pt-1 pb-1 border-bottom">{{ user.get_sex_display }}</div>
				<div class="col-3 pt-1 pb-1 border-bottom">是否启用：</div><div class="col-9 pt-1 pb-1 border-bottom">{% if user.enabled %}<span class="badge badge-success">启用</span>{% else %}<span class="badge badge-danger">禁用</span>{% endif %}</div>
				<div class="col-3 pt-1 pb-1 border-bottom">角色：</div><div class="col-9 pt-1 pb-1 border-bottom">{{ user.get_role_display }}</div>
				
				<div class="col-3 pt-1 pb-1 border-bottom">权限：</div>
				<div class="col-9 pt-1 pb-1 border-bottom">
					<ul id="ztree-permissions" class="ztree"></ul>
				</div>
				
				<div class="col-3 pt-1 pb-1 border-bottom">所属组：</div>
				<div class="col-9 pt-1 pb-1 border-bottom">
				{% if user.groups.all %}
					{% if request|has_permission:'组详细' %}
						{% for group in user.groups.all %}
							<a href="{% url 'user:group' group.id %}" class="btn btn-sm btn-success">{{ group.group_name }}</a>&nbsp;&nbsp;
						{% endfor %}
					{% else %}
						{% for group in user.groups.all %}
							<a href="javascript:void(0)" class="btn btn-sm btn-success">{{ group.group_name }}</a>&nbsp;&nbsp;
						{% endfor %}
					{% endif %}
				{% else %}
				{% endif %}
				</div>

				<div class="col-3 pt-1 pb-1 border-bottom">拥有主机数：</div><div class="col-9 pt-1 pb-1 border-bottom">{{ user.remote_user_bind_hosts.all.count }}</div>
				<div class="col-3 pt-1 pb-1 border-bottom">创建时间：</div><div class="col-9 pt-1 pb-1 border-bottom">{{ user.create_time | date:"Y/m/d H:i:s" }}</div>
				<div class="col-3 pt-1 pb-1 border-bottom">最后登录时间：</div><div class="col-9 pt-1 pb-1 border-bottom">{{ user.last_login_time | date:"Y/m/d H:i:s" | default:'' }}</div>
				<div class="col-3 pt-1 pb-1">备注：</div><div class="col-9 pt-1 pb-1">{{ user.memo | default:'' }}</div>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card --> 
		  {% endblock content %}

{% block js %}
<!-- DataTables -->
<script src="{% static 'adminlte/plugins/datatables/jquery.dataTables.js' %}"></script>
<script src="{% static 'adminlte/plugins/datatables/dataTables.bootstrap4.js' %}"></script>
<script>
$("#datatables-lists").DataTable({
	language: {
		"sProcessing": "处理中...",
		"sLengthMenu": "显示 _MENU_ 项结果",
		"sZeroRecords": "没有匹配结果",
		"sInfo": "显示第 _START_ 至 _END_ 项结果，共 _TOTAL_ 项",
		"sInfoEmpty": "显示第 0 至 0 项结果，共 0 项",
		"sInfoFiltered": "(由 _MAX_ 项结果过滤)",
		"sInfoPostFix": "",
		"sSearch": "搜索:",
		"sUrl": "",
		"sEmptyTable": "表中数据为空",
		"sLoadingRecords": "载入中...",
		"sInfoThousands": ",",
		"oPaginate": {
			"sFirst": "首页",
			"sPrevious": "上页",
			"sNext": "下页",
			"sLast": "末页"
		},
		"oAria": {
			"sSortAscending": ": 以升序排列此列",
			"sSortDescending": ": 以降序排列此列"
		}
	},
	destroy: true,	// 允许重建
	bProcessing:true,  // 表格数据过多处理时显示: sProcessing
	lengthMenu: [[10, 25, 50, 100, -1], [10, 25, 50, 100, "全部"]],
	order: [],
	 //scrollY: 480,	// 滚动条
	 //scrollCollapse: true,
	 //jQueryUI: true,
	 stateSave: true,	// 保存最后一次分页信息、排序信息，当页面刷新，或者重新进入这个页面，恢复上次的状态。
	 stateDuration: 86400,	// 本地储存(0~更大)还是session储存(-1) 
});
</script>

<script src="{% static 'ztree/js/jquery.ztree.all.min.js' %}"></script>
<script>
	var setting = {
		data: {
			simpleData: {
				enable: true
			}
		}
	};

	var zNodes =[
		{
			name: "全部",
			open: true,
			children: {{ user.permission.all | permission_to_ztree | safe }}
		}
	];

	$(document).ready(function(){
		zTree = $.fn.zTree.init($("#ztree-permissions"), setting, zNodes);
	});
	
</script>

{% endblock js %}